site_name: Andreas Karis Blog
site_description: Andreas Karis' blog about anything Kubernetes, OpenShift, Linux and Networking
site_url: https://andreaskaris.github.io/blog/
theme: 
  name: material
  custom_dir: overrides
  palette:
    primary: black
    accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.top
    - navigation.path
    - navigation.indexes
plugins:
  - git-revision-date-localized
  - rss:
      match_path: '^(?!.*index).*$'
  - blogging:
      dirs:
        - ceph
        - openshift
        - linux
        - networking
        - openstack
        - coding
      categories:
        - name: ceph
          dirs:
            - ceph
        - name: linux
          dirs:
            - linux
        - name: networking
          dirs:
            - networking
        - name: openstack
          dirs:
            - openstack
        - name: openshift
          dirs:
            - openshift
        - name: coding
          dirs:
            - coding
# hide:
#   - toc
markdown_extensions:
  - pymdownx.highlight:
      guess_lang: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth : "0"
nav:
- Home: index.md
- Ceph:
  - ceph/index.md
  - Ceph manual test with qemu: ceph/ceph-manual-test.md
- Linux:
  - linux/index.md
  - cgroups: linux/cgroups.md
  - Containers in Linux: linux/containers.md
  - Hugepages: linux/hugepages.md
  - iPXE boot environment on Fedora: linux/ipxe-boot-environment.md
  - Java Idrac Issues: linux/java-idrac-issues.md
  - meson: linux/meson.md
  - namespaces: linux/namespaces.md
  - Old Java inside a container with xorgs: linux/old_java_version_with_xorgs_in_container.md
  - Workaround for org.gnome.shell.overrides not installed: linux/org-gnome-shell-overrides.md
  - Retrieving process cgroup resource usage and limit info: linux/get-process-cgroup-info-and-limits.md
  - RHEL Booting a virtual machine with UEFI but without secure boot: linux/libvirt-uefi-without-secureboot.md
  - Setting journalctl limits: linux/setting-journalctl-limits.md
  - Using cgroups for CFS bandwidth control: linux/cgroups_cpu_quota.md
  - udev rules to apply ethtool settings: linux/udev-ethtool.md
- Networking:
  - networking/index.md
  - Accept Source Routing: networking/accept-source-routing.md
  - ARP and the Neighbor table: networking/arp_and_the_neighbor_table.md
  - BPF and tcpdump: networking/bpf-and-tcpdump.md
  - Bonding in Linux: networking/bonding_in_linux.md  
  - Configure Juniper switch: networking/juniper_x520.md
  - Hands-on with OVN Interconnection: networking/ovn-interconnection.md
  - haproxy and HTTP/2: networking/haproxy-and-h2c.md
  - Install Open vSwitch on Rocky Linux 8: networking/install-openvswitch-on-rocky.md
  - Geneve tunneling: networking/geneve_tunneling.md
  - Netlink: networking/netlink.md  
  - OVN standalone on Fedora: networking/ovn_standalone_on_fedora.md
  - OVS packet recirculation: networking/ovs_recirculation.md
  - OVS VXLAN tunnels and DSCP: networking/ovs-vxlan-tunnels-and-dscp.md
  - OVS with GDB: networking/ovs_with_gdb.md
  - Packet tracing with OVN: networking/packet-tracing-with-ovn.md  
  - SCTP: networking/sctp.md
  - Useful commands: networking/useful-commands.md
  - Wireguard: networking/wireguard.md
- OpenShift and Kubernetes:
  - openshift/index.md
  - AlertManager: openshift/alertmanager.md
  - Analyzing CNI calls: openshift/analyzing-cni.md
  - Building custom release images for OpenShift: openshift/ocp-custom-release-image.md
  - CPU manager with custom MachineConfigPool: openshift/cpu-manager-with-custom-machine-config-pool.md
  - CPU isolation in Red Hat OpenShift Container Platform: openshift/cpu-isolation-in-openshift.md
  - Crio vs conmon vs runc: openshift/crio-conmon-runc.md  
  - DedicatedServiceMonitors in OpenShift Monitoring: openshift/dedicated-service-monitors.md
  - Etcd Performance tests: openshift/etcd_perf.md
  - Get vs List API Calls:  openshift/get-vs-list-api-calls.md
  - Httpbin tshark sidecar container: openshift/openshift_httpbin_tshark_sidecar.md
  - Hints for installing kubernetes on Fedora: openshift/kubernetes_cluster.md
  - Horizontal Pod Autoscaler: openshift/HPA.md
  - How RHCOS updates work: openshift/how_rhcos_updates_work.md
  - How kubelet monitors filesystems: openshift/kubelet-filesystems.md
  - Infra nodes with MachineSets without worker label: openshift/ocp4-infra-nodes-with-machineset-without-worker-label.md
  - Ingress Controller Sharding OCP on OSP: openshift/ingresscontroller_router_sharding_ocp_on_osp.md
  - Ingress Controller Sharding on separate VIP: openshift/ingress-controller-sharding-on-separate-vip.md
  - Installing a cluster with a mirror registry: openshift/openshift_mirror_registry.md
  - Istio 1.6 on OpenShift 4.x: openshift/istio-1.6-on-ocp.4.x.md
  - kata containers and the kata operatora: openshift/kata.md  
  - kernel-ml on OpenShift: openshift/kernel-ml-on-openshift.md
  - Kind with OVN Kubernetes Hybrid Overlay: openshift/ovn-kind-hybrid-overlay.md
  - Kind with private registry: openshift/kind-with-private-registry.md
  - List container images in registry: openshift/list_docker_registry_containers.md
  - Mount a container image: openshift/mounting-container-image.md
  - OpenShift on OpenStack: openstack/install_openshift_on_openstack.md
  - OpenShift with iSCSI multipath: openshift/openshift-with-multipath.md
  - Patch status.loadBalancer.ingress IP manually: openshift/patch-service-loadbalancer-ingress-ip.md
  - Private container registry: openshift/private-registry.md
  - Proxy OCP 4.5: openshift/proxy-ocp-4.5.md
  - rpm-ostreed failed to find image: openshift/rpm-ostree-failed-to-find-image.md
  - Seccomp defaults in Red Hat OpenShift Container Platform: openshift/seccomp-defaults-ocp.md
  - Security Context Constraints (SCC): openshift/scc.md
  - "SCCs and mutating webhooks - a lesson learned": openshift/openshift-scc-with-mutating-webhooks.md
  - SElinux labels fix: openshift/fix-selinux-labels-coreos.md
  - SCTP: networking/sctp.md
  - Troubleshooting etcd state: openshift/openshift_troubleshooting_etcd_state.md
  - Useful commands for OpenShift: openshift/useful-ocp-commands.md
  - Useful commands for OpenShift SDN: openshift/useful-ocp-sdn-commands.md
  - Troubleshooting OpenShift on OpenStack worker creation: openshift/troubleshooting_openshift_on_openstack_worker_creation.md
- OpenStack:
  - openstack/index.md
  - Reattach to running deployment: openstack/reattach_to_running_deployment.md
  - Using clouds.yaml: openstack/using_clouds_yaml.md
- Coding:
  - coding/index.md
  - Controller Reconciliation: coding/operator-sdk-reconciliation.md
  - My vimrc: coding/vimrc.md
  - Golang IP address conversion: coding/golang-ip-conversion.md
