site_name: Andreas Karis Blog
theme: 
  name: mkdocs
nav:
- Home: index.md
- Ceph:
  - Ceph manual test with qemu: ceph/ceph-manual-test.md
- Containers:
  - cgroups: linux/cgroups.md
  - Containers in Linux: linux/containers.md
  - List container images in registry: openshift/list_docker_registry_containers.md
  - namespaces: linux/namespaces.md
- Linux:
  - cgroups: linux/cgroups.md
  - Containers in Linux: linux/containers.md
  - Hugepages: linux/hugepages.md
  - meson: linux/meson.md
  - namespaces: linux/namespaces.md
  - Old Java inside a container with xorgs: linux/old_java_version_with_xorgs_in_container.md
- Networking:
  - ARP and the Neighbor table: networking/arp_and_the_neighbor_table.md
  - Bonding in Linux: networking/bonding_in_linux.md  
  - Geneve tunneling: networking/geneve_tunneling.md
  - Configure Juniper switch: networking/juniper_x520.md
  - Netlink: networking/netlink.md  
  - OVN kind: networking/ovn-kind.md
  - OVN standalone on Fedora 31: networking/ovn_standalone_on_fedora31.md
  - OVS packet recirculation: networking/ovs_recirculation.md
  - OVS VXLAN tunnels and DSCP: networking/ovs-vxlan-tunnels-and-dscp.md
  - OVS with GDB: networking/ovs_with_gdb.md
  - SCTP: networking/sctp.md
  - Wireguard: networking/wireguard.md
- OpenShift:
  - AlertManager: openshift/alertmanager.md
  - CPU manager with custom MachineConfigPool: openshift/cpu-manager-with-custom-machine-config-pool.md
  - Crio vs conmon vs runc: openshift/crio-conmon-runc.md  
  - Httpbin tshark sidecar container: openshift/openshift_httpbin_tshark_sidecar.md
  - Hints for installing kubernetes on Fedora: openshift/kubernetes_cluster.md
  - Infra nodes with MachineSets without worker label: openshift/ocp4-infra-nodes-with-machineset-without-worker-label.md
  - Ingress Controller Sharding OCP on OSP: openshift/ingresscontroller_router_sharding_ocp_on_osp.md
  - Ingress Controller Sharding on separate VIP: openshift/ingress-controller-sharding-on-separate-vip.md
  - Installing a cluster with a mirror registry: openshift/openshift_mirror_registry.md
  - Istio 1.6 on OpenShift 4.x: openshift/istio-1.6-on-ocp.4.x.md
  - kata containers and the kata operatora: openshift/kata.md  
  - Proxy OCP 4.5: openshift/proxy-ocp-4.5.md
  - Security Context Constraints (SCC): openshift/scc.md
  - SCTP: networking/sctp.md
  - Troubleshooting etcd state: openshift/openshift_troubleshooting_etcd_state.md
  - Querying the OCP 4.x upgrades info API: openshift/useful-ocp-curl.md
  - Troubleshooting OpenShift on OpenStack worker creation: openshift/troubleshooting_openshift_on_openstack_worker_creation.md
- OpenStack:
  - Reattach to running deployment: openstack/reattach_to_running_deployment.md
  - Using clouds.yaml: openstack/using_clouds_yaml.md

